export const globalConfig = [
  // ✅ 수입 데이터
  {
    type: "income",
    date: "2025-03-01",
    price: 10000,
    category: "용돈",
    asset: "토스뱅크",
    memo: "엄마 용돈",
  },
  {
    type: "income",
    date: "2025-03-05",
    price: 25000,
    category: "급여",
    asset: "카카오뱅크",
    memo: "파트타임",
  },
  {
    type: "income",
    date: "2025-03-08",
    price: 5000,
    category: "기타",
    asset: "농협",
    memo: "당근마켓 수입",
  },
  {
    type: "income",
    date: "2025-04-08",
    price: 15000,
    category: "기타",
    asset: "농협",
    memo: "당근마켓 수입",
  },
  {
    type: "income",
    date: "2025-04-05",
    price: 25000,
    category: "급여",
    asset: "카카오뱅크",
    memo: "파트타임",
  },

  // ✅ 지출 데이터
  {
    type: "expend",
    date: "2025-03-02",
    price: 7000,
    category: "카페",
    asset: "토스뱅크",
    memo: "스타벅스",
  },
  {
    type: "expend",
    date: "2025-03-03",
    price: 12000,
    category: "식비",
    asset: "카카오뱅크",
    memo: "점심 식사",
  },
  {
    type: "expend",
    date: "2025-03-07",
    price: 4000,
    category: "교통",
    asset: "카카오뱅크",
    memo: "버스비",
  },
  {
    type: "expend",
    date: "2025-03-10",
    price: 9000,
    category: "편의점",
    asset: "농협",
    memo: "야식",
  },
  {
    type: "expend",
    date: "2025-04-10",
    price: 8000,
    category: "편의점",
    asset: "농협",
    memo: "야식",
  },{
    type: "expend",
    date: "2025-04-10",
    price: 12000,
    category: "교통",
    asset: "카카오뱅크",
    memo: "버스비",
  },
];
